version: 0.2

#builds access.analyser project in aws code build

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       dotnet: latest
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - echo "start of restore"
       - dotnet restore
      # - command
  build:
    commands:
       - echo "start of build"
       - dotnet build access.analyser
       - echo "start of test"
       - dotnet test UnitTests
      # - command
  post_build:
    commands:
       - echo "start of publish"
       - dotnet publish --configuration Release access.analyser
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
     - access.analyser/bin/Release/netcoreapp3.1/publish/*
     - appspec.yml
     - scripts/**/*
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths